# Generated by Django 4.2.11 on 2026-04-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='half_day_end',
            field=models.BooleanField(default=False, help_text='Si vrai, absent uniquement le matin du jour de fin.'),
        ),
        migrations.AddField(
            model_name='absencerequest',
            name='half_day_start',
            field=models.BooleanField(default=False, help_text="Si vrai, absent uniquement l'après-midi du jour de début."),
        ),
    ]
