# Generated by Django 4.2.11 on 2026-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_absencerequest_half_day_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerequest',
            name='user_comment',
            field=models.TextField(blank=True, help_text="Commentaire libre laissé par l'employé à la soumission."),
        ),
    ]
