# Generated by Django 4.2.11 on 2026-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_absencerequest_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['user', 'absence_type', 'status'], name='absences_ab_user_id_27c5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['user', 'date_start', 'date_end'], name='absences_ab_user_id_cd14cd_idx'),
        ),
    ]
