# Generated by Django 4.2.11 on 2026-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('REMOTE', 'Télétravail'), ('FIELD', 'Mission externe')], max_length=10)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_radius_meters', models.PositiveIntegerField(blank=True, help_text='Rayon GPS pour cette mission (None = pas de validation GPS).', null=True)),
                ('qr_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('manager_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
