# Generated by Django 4.2.11 on 2026-04-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='user_comment',
            field=models.TextField(blank=True, help_text="Commentaire libre laissé par l'employé à la soumission (contexte, motif, instructions spéciales)."),
        ),
    ]
