# Generated by Django 4.2.11 on 2026-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_mission_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_number',
            field=models.CharField(blank=True, help_text='Numéro de mission attribué par le manager / mission manager / admin.', max_length=40),
        ),
    ]
