# Generated by Django 4.2.11 on 2026-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_mission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='travel_minutes_actual',
            field=models.PositiveIntegerField(blank=True, help_text="Trajet aller domicile → mission, en minutes (snapshot à l'approbation).", null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='travel_minutes_compensable',
            field=models.PositiveIntegerField(blank=True, help_text='Temps de trajet A/R compensé : max(0, (actual − standard_commute) × 2). Ajouté au temps de mission pour le calcul des heures.', null=True),
        ),
    ]
