# Generated by Django 4.2.11 on 2026-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_add_travel_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['user', 'status'], name='missions_mi_user_id_078df3_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['user', 'date_start', 'date_end'], name='missions_mi_user_id_4f65a4_idx'),
        ),
    ]
