# Generated by Django 4.2.11 on 2026-04-21 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQRAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_token', models.CharField(max_length=64)),
                ('new_token', models.CharField(max_length=64)),
                ('regenerated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('regenerated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_regenerations', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_audits', to='users.site')),
            ],
            options={
                'ordering': ['-regenerated_at'],
            },
        ),
    ]
