# Generated by Django 4.2.11 on 2026-04-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_siteqraudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_site',
            field=models.ForeignKey(blank=True, help_text='Site de rattachement principal du collaborateur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.site'),
        ),
        migrations.CreateModel(
            name='SiteHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.site')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='siteholiday',
            constraint=models.UniqueConstraint(fields=('site', 'date'), name='unique_holiday_per_site_date'),
        ),
    ]
