# Generated by Django 4.2.11 on 2026-04-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_home_site_siteholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GPS', 'Géolocalisation pour pointage'), ('STORAGE', 'Stockage local de la session (JWT)'), ('PRIVACY_POLICY', 'Politique de confidentialité')], max_length=32)),
                ('granted', models.BooleanField()),
                ('policy_version', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'kind', '-created_at'], name='users_conse_user_id_bddd6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Modification utilisateur'), ('USER_DELETE', 'Suppression / anonymisation utilisateur'), ('ROLE_CHANGE', 'Changement de rôle'), ('SESSION_EDIT', "Édition d'un pointage"), ('ABSENCE_DECISION', 'Décision sur une absence'), ('MISSION_DECISION', 'Décision sur une mission'), ('DATA_EXPORT', 'Export de données utilisateur'), ('SITE_QR_ROTATE', 'Rotation QR site')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text="Qui a effectué l'action (null si système).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text="Sur quel utilisateur l'action a porté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', '-created_at'], name='users_admin_target__865ed7_idx'), models.Index(fields=['action', '-created_at'], name='users_admin_action_3a1355_idx')],
            },
        ),
    ]
