# Generated by Django 4.2.11 on 2026-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_consentlog_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mission_manager',
            field=models.BooleanField(default=False, help_text='Peut attribuer et valider des missions transversalement (tous sites).'),
        ),
    ]
