# Generated by Django 4.2.11 on 2026-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_data_purged_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude du domicile, sélectionnée sur carte par l'admin.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude du domicile, sélectionnée sur carte par l'admin.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='standard_commute_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Trajet standard domicile → site de rattachement, ALLER SIMPLE en minutes. Recalculé automatiquement quand l'adresse domicile ou le site changent ; éditable manuellement par l'admin.", null=True),
        ),
    ]
