# Generated by Django 4.2.11 on 2026-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_home_address_and_commute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Modification utilisateur'), ('USER_DELETE', 'Suppression / anonymisation utilisateur'), ('ROLE_CHANGE', 'Changement de rôle'), ('SESSION_EDIT', "Édition d'un pointage"), ('SESSION_DELETE', "Suppression d'un pointage"), ('ABSENCE_DECISION', 'Décision sur une absence'), ('MISSION_DECISION', 'Décision sur une mission'), ('DATA_EXPORT', 'Export de données utilisateur'), ('SITE_QR_ROTATE', 'Rotation QR site'), ('DATA_PURGED', 'Purge rétention LPD')], max_length=32),
        ),
    ]
