# Generated by Django 4.2.11 on 2026-04-23 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_session_delete_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Modification utilisateur'), ('USER_DELETE', 'Suppression / anonymisation utilisateur'), ('ROLE_CHANGE', 'Changement de rôle'), ('SESSION_EDIT', "Édition d'un pointage"), ('SESSION_DELETE', "Suppression d'un pointage"), ('DELETION_REQUEST_CREATED', 'Demande de suppression compte (employé)'), ('DELETION_REQUEST_APPROVED', 'Demande approuvée (anonymisation effectuée)'), ('DELETION_REQUEST_REJECTED', 'Demande refusée'), ('ABSENCE_DECISION', 'Décision sur une absence'), ('MISSION_DECISION', 'Décision sur une mission'), ('DATA_EXPORT', 'Export de données utilisateur'), ('SITE_QR_ROTATE', 'Rotation QR site'), ('DATA_PURGED', 'Purge rétention LPD')], max_length=32),
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reason', models.TextField(blank=True, help_text='Motif libre laissé par le collaborateur (optionnel).')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée et anonymisation effectuée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='datadeletionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_deletion_request_per_user'),
        ),
    ]
