# Generated by Django 4.2.11 on 2026-04-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_data_deletion_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Raison sociale (ex : Acme SA).', max_length=200)),
                ('legal_form', models.CharField(blank=True, help_text='Forme juridique (SA, Sàrl, AG, GmbH, association, …).', max_length=20)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Suisse', max_length=80)),
                ('dpo_contact_email', models.EmailField(blank=True, help_text='Email de contact pour les questions liées à la protection des données (Art. 14 LPD — contact du responsable).', max_length=254)),
                ('dpo_contact_phone', models.CharField(blank=True, max_length=40)),
                ('privacy_policy_extra', models.TextField(blank=True, help_text='Texte libre ajouté en bas de la politique de confidentialité (ex : mentions sectorielles, sous-traitants spécifiques).')),
                ('logo_data_url', models.TextField(blank=True, help_text='Logo en data URL base64 (data:image/png;base64,…). Limite recommandée : 150 KB (256 px max).')),
                ('primary_color', models.CharField(blank=True, default='#1e3a5f', help_text='Couleur primaire (hex, ex : #1e3a5f). Injectée comme var CSS --brand-primary au boot frontend.', max_length=9)),
                ('secondary_color', models.CharField(blank=True, default='#10b981', help_text='Couleur secondaire (accents).', max_length=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres entreprise',
                'verbose_name_plural': 'Paramètres entreprise',
            },
        ),
    ]
