# Generated by Django 4.2.11 on 2026-05-15 16:26

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_company_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Libellé (ex: Heures supplémentaires)', max_length=100)),
                ('day_type', models.CharField(choices=[('ALL', 'Tous les jours'), ('WEEKDAY', 'Jours ouvrés (lun–ven)'), ('WEEKEND', 'Weekend (sam–dim)'), ('HOLIDAY', 'Jours fériés')], default='ALL', max_length=10)),
                ('threshold_minutes', models.PositiveIntegerField(default=510, help_text='Seuil de déclenchement en minutes (ex: 510 = 8h30).')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Taux de majoration (ex: 1.25 = 125%).', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'application (plus petit = prioritaire).")),
            ],
            options={
                'verbose_name': 'Règle de majoration',
                'verbose_name_plural': 'Règles de majoration',
                'ordering': ['order', 'threshold_minutes'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_lock_day', models.PositiveSmallIntegerField(default=10, help_text='Après ce jour du mois, le mois précédent est verrouillé.')),
                ('lock_bypass_roles', models.CharField(choices=[('superuser', 'Superuser uniquement'), ('manager', 'Manager et superuser'), ('any', 'Tous les utilisateurs')], default='superuser', help_text='Rôles autorisés à modifier un mois verrouillé.', max_length=20)),
                ('break_trigger_minutes', models.PositiveIntegerField(default=360, help_text='Durée travaillée (min) déclenchant la pause obligatoire (360 = 6h).')),
                ('break_duration_minutes', models.PositiveIntegerField(default=30, help_text='Durée de la pause obligatoire en minutes.')),
                ('paid_break_minutes', models.PositiveIntegerField(default=0, help_text='Minutes de pause considérées comme travaillées (pause payée).')),
                ('auto_deduct_break', models.BooleanField(default=False, help_text='Déduire automatiquement la pause du temps travaillé.')),
                ('daily_min_minutes', models.PositiveIntegerField(default=0, help_text='Durée minimale journalière en minutes.')),
                ('daily_max_minutes', models.PositiveIntegerField(default=630, help_text='Durée maximale journalière en minutes (630 = 10h30).')),
                ('eve_holiday_reduced_minutes', models.PositiveIntegerField(default=0, help_text='Durée réduite les veilles de jours fériés (0 = désactivé).')),
            ],
            options={
                'verbose_name': 'Politique de temps de travail',
                'verbose_name_plural': 'Politique de temps de travail',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_locked_months',
            field=models.BooleanField(default=False, help_text='Autorisé à modifier des pointages sur des mois verrouillés.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exempt_from_clocking',
            field=models.BooleanField(default=False, help_text='Non soumis au timbrage (planification = preuve de présence).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager direct (utilisé pour les notifications email).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
