# Generated by Django 4.2.11 on 2026-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_consent_withdrawal_request_and_must_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATE', 'Création utilisateur'), ('USER_UPDATE', 'Modification utilisateur'), ('USER_DELETE', 'Suppression / anonymisation utilisateur'), ('ROLE_CHANGE', 'Changement de rôle'), ('SESSION_EDIT', "Édition d'un pointage"), ('SESSION_DELETE', "Suppression d'un pointage"), ('DELETION_REQUEST_CREATED', 'Demande de suppression compte (employé)'), ('DELETION_REQUEST_APPROVED', 'Demande approuvée (anonymisation effectuée)'), ('DELETION_REQUEST_REJECTED', 'Demande refusée'), ('ABSENCE_DECISION', 'Décision sur une absence'), ('MISSION_DECISION', 'Décision sur une mission'), ('DATA_EXPORT', 'Export de données utilisateur'), ('SITE_QR_ROTATE', 'Rotation QR site'), ('DATA_PURGED', 'Purge rétention LPD'), ('CONSENT_WITHDRAWAL_CREATED', 'Demande retrait consentement (employé)'), ('CONSENT_WITHDRAWAL_APPROVED', 'Retrait consentement approuvé'), ('CONSENT_WITHDRAWAL_REJECTED', 'Retrait consentement refusé'), ('CONSENT_INITIAL_ACCEPTED', 'Consentements initiaux acceptés')], max_length=32),
        ),
    ]
