# Generated by Django 4.2.11 on 2026-05-19 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAddressChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_home_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('new_home_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('new_address_label', models.CharField(blank=True, help_text='Étiquette humaine (rue, code postal, ville).', max_length=300)),
                ('user_reason', models.TextField(blank=True, help_text='Motif libre laissé par le collaborateur (déménagement, etc.).')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=10)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_home_address_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_address_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='homeaddresschangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_home_address_change_per_user'),
        ),
    ]
