# Generated by Django 4.2.11 on 2026-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_rounded', models.DateTimeField()),
                ('clock_out_rounded', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('OFFICE', 'Bureau'), ('REMOTE', 'Télétravail'), ('MISSION', 'Mission externe')], default='OFFICE', max_length=10)),
                ('gps_lat_in', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lon_in', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lat_out', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lon_out', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('justification', models.TextField(blank=True)),
                ('justification_approved', models.BooleanField(blank=True, null=True)),
                ('is_forgotten', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-clock_in'],
            },
        ),
        migrations.CreateModel(
            name='FixedTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
