# Generated by Django 4.2.11 on 2026-04-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('clocking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocksession',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='missions.mission'),
        ),
    ]
