# Generated by Django 4.2.11 on 2026-04-21 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('clocking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocksession',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='users.site'),
        ),
        migrations.AddField(
            model_name='clocksession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clocksession',
            index=models.Index(fields=['user', 'clock_in'], name='clocking_cl_user_id_1e64ff_idx'),
        ),
        migrations.AddIndex(
            model_name='clocksession',
            index=models.Index(fields=['clock_out'], name='clocking_cl_clock_o_55612b_idx'),
        ),
    ]
