# Generated by Django 4.2.11 on 2026-05-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clocking', '0004_alert_alert_unique_alert_per_session_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Delta pondéré en heures (positif = sup, négatif = déficit).', max_digits=6)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_overtime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime quotidien',
                'verbose_name_plural': 'Overtime quotidiens',
                'indexes': [models.Index(fields=['user', 'date'], name='clocking_da_user_id_e1d7d0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyovertime',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_overtime_per_user_day'),
        ),
    ]
