# Generated by Django 4.2.11 on 2026-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocking', '0005_add_daily_overtime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clocksession',
            index=models.Index(condition=models.Q(('clock_out__isnull', True)), fields=['user', '-clock_in'], name='cs_user_open_idx'),
        ),
        migrations.AddIndex(
            model_name='clocksession',
            index=models.Index(fields=['user', 'clock_in', 'clock_out'], name='clocking_cl_user_id_b4a68c_idx'),
        ),
    ]
